"""fix room unique constraint per hotel

Revision ID: e8198fd4bf09
Revises: 0475f8406974
Create Date: 2026-04-14 17:45:20.247384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8198fd4bf09'
down_revision: Union[str, Sequence[str], None] = '0475f8406974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rooms_number_key'), 'rooms', type_='unique')
    op.create_unique_constraint('uq_room_hotel_number', 'rooms', ['hotel_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_room_hotel_number', 'rooms', type_='unique')
    op.create_unique_constraint(op.f('rooms_number_key'), 'rooms', ['number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
